services:
  # 1. PostgreSQL 데이터베이스
  postgres:
    image: 'postgres:16-alpine'
    container_name: postgres-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432' # 외부에서도 접속 가능하도록 매핑
    volumes:
      - ./postgres_data:/var/lib/postgresql
    networks:
      - hear-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Redis 캐시/메시지 브로커
  redis:
    image: 'redis:7-alpine'
    container_name: redis-cache
    ports:
      - '6379:6379'
    networks:
      - hear-network

  # 3. 코틀린 스프링 부트 애플리케이션
  app:
    build: .
    image: 'kusuri12/hear-spring-application:1.0'
    profiles:
      - prod
    container_name: hear-app
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - hear-network

networks:
  hear-network:
    driver: bridge