spring:
  application:
    name: hear

  messages:
    encoding: UTF-8

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  # PostgreSQL
  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:postgresql://postgres:5432/${POSTGRES_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA & Hibernate
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: ${JPA_SHOW_SQL:false}
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100

  # Redis & Cache
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis

  # mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # OAuth2
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            scope: profile, email
#      resourceserver:
#        jwt:
#          issuer-uri: https://accounts.google.com

  # Docker Compose Support
  docker:
    compose:
      enabled: true
      file: compose.yaml

  # aws cloud
  cloud.aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET}

# jwt
jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600}  # seconds
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:2592000}  # 30 days

# openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: ASC
  api-docs:
    path: /api-docs

# sentry
sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0
  logging:
    minimum-event-level: error
    minimum-breadcrumb-level: info

# openfeign
feign:
  client:
    config:
      default:
        loggerLevel: ${OPENFEIGN_LOGGER_LEVEL:BASIC}
        connectTimeout: 5000
        readTimeout: 5000
      holiday-api:
        loggerLevel: BASIC
        connectTimeout: 3000
        readTimeout: 10000
        retryer: feign.Retryer.Default

api:
  discord.webhook:
    url: ${DISCORD_WEBHOOK_URL}
  holiday:
    url: ${HOLIDAY_SERVICE_URL}
    service-key: ${HOLIDAY_SERVICE_KEY}

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR