spring:
  application:
    name: hear

  messages:
    encoding: UTF-8

  # PostgreSQL
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 0
      connection-timeout: 20000

  # JPA & Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100

  # Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true

  # Redis & Cache
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis

  # mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Docker Compose Support
  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start_only  # 실행 유지
      readiness:
        wait: never

  # aws cloud
  cloud.aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET}

# jwt
jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600}  # seconds
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:2592000}  # 30 days

# openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: ASC
  api-docs:
    path: /api-docs

# sentry
sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0
  logging:
    minimum-event-level: error
    minimum-breadcrumb-level: info

# openfeign
feign:
  client:
    config:
      default:
        loggerLevel: ${OPENFEIGN_LOGGER_LEVEL:BASIC}
        connectTimeout: 5000
        readTimeout: 5000
      holiday-api:
        loggerLevel: BASIC
        connectTimeout: 3000
        readTimeout: 10000
        retryer: feign.Retryer.Default

api:
  discord.webhook:
    url: ${DISCORD_WEBHOOK_URL}
  holiday:
    url: ${HOLIDAY_SERVICE_URL}
    service-key: ${HOLIDAY_SERVICE_KEY}

logging:
  level:
    root: ERROR
    modeep.hear: INFO

external.api:
    base-url: ${INTERNAL_API_URL:https://api.default-service.com}
    timeout: 5000