name: "🐛 Bug Report"
description: "발생한 버그를 보고합니다."
title: "bug/"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "description"
    validations:
      required: true
  - type: input
    id: scope
    attributes:
      label: "scope"
      placeholder: "e.g. Auth Service, API-Gateway"
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: "etc"