name: "⚙️ Chore"
description: "빌드 설정, 패키지 관리, 환경 설정 등 기타 운영 작업입니다."
title: "chore/"
labels: ["chore"]
body:
  - type: textarea
    id: description
    attributes:
      label: "description"
    validations:
      required: true
  - type: input
    id: scope
    attributes:
      label: "scope"
      placeholder: "e.g. CI/CD, Dependencies"
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: "etc"