name: "🚀 Feature Request"
description: "새로운 기능을 제안하거나 기존 기능을 개선합니다."
title: "[FEAT] "
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: "description"
    validations:
      required: true
  - type: input
    id: scope
    attributes:
      label: "scope"
      placeholder: "e.g. AI Diary, Sticker System"
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: "etc"