name: "♻️ Refactor"
description: "기능 변경 없이 코드 구조나 가독성을 개선하는 작업입니다."
title: "[REFACTOR] "
labels: ["refactor"]
body:
  - type: textarea
    id: description
    attributes:
      label: "description"
    validations:
      required: true
  - type: input
    id: scope
    attributes:
      label: "scope"
      placeholder: "e.g. Repository Layer, DTO structure"
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: "etc"